#!/usr/bin/env python3
import os
import re

root = r"C:\Users\mitch\AppData\Local\Temp\opencode\TelosTax"

replacements = [
    # localStorage keys
    ("telostax:returns", "hatax:returns"),
    ("telostax:return:", "hatax:return:"),
    ("telostax:chat:", "hatax:chat:"),
    ("telostax:salt", "hatax:salt"),
    ("telostax:verify", "hatax:verify"),
    ("telostax:ai-settings", "hatax:ai-settings"),
    ("telostax:expense-scanner", "hatax:expense-scanner"),
    ("telostax:ai-key-enc", "hatax:ai-key-enc"),
    ("telostax:ai-key-migrate", "hatax:ai-key-migrate"),
    ("telostax:expense-scanner-enc", "hatax:expense-scanner-enc"),
    ("telostax:ai-key-enc", "hatax:ai-key-enc"),
    ("telostax:ai-settings", "hatax:ai-settings"),
    ("telostax:ai-key-migrate", "hatax:ai-key-migrate"),
    ("telostax:expense-scanner-enc", "hatax:expense-scanner-enc"),
    
    # File format
    ("telostax-export", "hatax-export"),
    (".telostax", ".hatax"),
    
    # IndexedDB
    ("telostax-privacy-log", "hatax-privacy-log"),
    
    # App name
    ("TelosTax", "HATax"),
    ("telostax", "hatax"),
    
    # PWA manifest
    ("TelosTax \u2014 Free Tax Preparation", "HATax \u2014 Professional Tax Preparation"),
    ("TelosTax \u2014 Professional Tax Preparation", "HATax \u2014 Professional Tax Preparation"),
    
    # PDF footers
    ("Prepared by TelosTax", "Prepared by HATax"),
    ("Generated by TelosTax", "Generated by HATax"),
    
    # PDF title
    ("TelosTax Filing Packet", "HATax Filing Packet"),
    
    # Calendar
    ("TelosTax Deadlines", "HATax Deadlines"),
    ("TelosTax//Tax Calendar", "HATax//Tax Calendar"),
    
    # Help content
    ("TelosTax can generate", "HATax can generate"),
    ("TelosTax is a preparation tool", "HATax is a preparation tool"),
    ("TelosTax JSON export", "HATax JSON export"),
    
    # File format
    (".telostax", ".hatax"),
    ("telostax-export-", "hatax-export-"),
    ("format: 'telostax-export'", "format: 'hatax-export'"),
    ("format: \"telostax-export\"", "format: \"hatax-export\""),
]

extensions = {'.ts', '.tsx', '.json', '.html', '.css', '.md'}

count = 0
for dirpath, dirnames, filenames in os.walk(r"C:\Users\mitch\AppData\Local\Temp\opencode\TelosTax"):
    # Skip excluded directories
    if any(x in dirpath for x in ('node_modules', 'dist', '.git', 'package-lock.json')):
        continue
    
    for fname in filenames:
        ext = os.path.splitext(fname)[1]
        if ext not in {'.ts', '.tsx', '.json', '.html', '.css', '.md'}:
            continue
        
        fpath = os.path.join(dirpath, fname)
        try:
            with open(fpath, 'r', encoding='utf-8') as f:
                content = f.read()
        except:
            continue
        
        original = content
        for find, replace in replacements:
            content = content.replace(find, replace)
        
        if content != original:
            with open(fpath, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"Updated: {fpath}")
            count += 1

print(f"Total files updated: {count}")