param(
    [string]$RootPath = "C:\Users\mitch\AppData\Local\Temp\opencode\TelosTax"
)

$files = Get-ChildItem -Recurse -Path $RootPath -Include "*.ts","*.tsx","*.json","*.html","*.css","*.md" | Where-Object { 
    $_.FullName -notmatch "node_modules|dist|\.git|package-lock.json" 
}

$replacements = @(
    "telostax:returns", "hatax:returns"
    "telostax:return:", "hatax:return:"
    "telostax:chat:", "hatax:chat:"
    "telostax:salt", "hatax:salt"
    "telostax:verify", "hatax:verify"
    "telostax:ai-settings", "hatax:ai-settings"
    "telostax:expense-scanner", "hatax:expense-scanner"
    "telostax:ai-key-enc", "hatax:ai-key-enc"
    "telostax:ai-key-migrate", "hatax:ai-key-migrate"
    "telostax:expense-scanner-enc", "hatax:expense-scanner-enc"
    "telostax:ai-key-enc", "hatax:ai-key-enc"
    "telostax:ai-settings", "hatax:ai-settings"
    "telostax:ai-key-migrate", "hatax:ai-key-migrate"
    "telostax:expense-scanner-enc", "hatax:expense-scanner-enc"
    "telostax-export", "hatax-export"
    ".telostax", ".hatax"
    "telostax-privacy-log", "hatax-privacy-log"
    "TelosTax", "HATax"
    "telostax", "hatax"
    "TelosTax — Free Tax Preparation", "HATax — Professional Tax Preparation"
    "TelosTax — Professional Tax Preparation", "HATax — Professional Tax Preparation"
    "Prepared by TelosTax", "Prepared by HATax"
    "Generated by TelosTax", "Generated by HATax"
    "TelosTax Filing Packet", "HATax Filing Packet"
    "TelosTax Deadlines", "HATax Deadlines"
    "TelosTax//Tax Calendar", "HATax//Tax Calendar"
    "TelosTax can generate", "HATax can generate"
    "TelosTax is a preparation tool", "HATax is a preparation tool"
    "TelosTax JSON export", "HATax JSON export"
    ".telostax", ".hatax"
    "telostax-export-", "hatax-export-"
    "format: 'telostax-export'", "format: 'hatax-export'"
)

$count = 0
foreach ($file in $files) {
    $content = Get-Content -Path $file.FullName -Raw
    $original = $content
    
    for ($i = 0; $i -lt $replacements.Count; $i += 2) {
        $find = $replacements[$i]
        $replace = $replacements[$i + 1]
        $content = $content -replace [regex]::Escape($find), $replace
    }
    
    if ($content -ne $original) {
        Set-Content -Path $file.FullName -Value $content -Encoding UTF8
        $count++
        Write-Host "Updated: $($file.FullName)"
    }
}

Write-Host "Total files updated: $count"