param(
    [string]$RootPath = "C:\Users\mitch\AppData\Local\Temp\opencode\HA Tax service"
)

$files = Get-ChildItem -Recurse -Path $RootPath -Include "*.ts","*.tsx","*.json","*.html","*.css","*.md" | Where-Object { 
    $_.FullName -notmatch "node_modules|dist|\.git|package-lock.json" 
}

$replacements = @(
    "HA Tax service:returns", "hatax:returns"
    "HA Tax service:return:", "hatax:return:"
    "HA Tax service:chat:", "hatax:chat:"
    "HA Tax service:salt", "hatax:salt"
    "HA Tax service:verify", "hatax:verify"
    "HA Tax service:ai-settings", "hatax:ai-settings"
    "HA Tax service:expense-scanner", "hatax:expense-scanner"
    "HA Tax service:ai-key-enc", "hatax:ai-key-enc"
    "HA Tax service:ai-key-migrate", "hatax:ai-key-migrate"
    "HA Tax service:expense-scanner-enc", "hatax:expense-scanner-enc"
    "HA Tax service:ai-key-enc", "hatax:ai-key-enc"
    "HA Tax service:ai-settings", "hatax:ai-settings"
    "HA Tax service:ai-key-migrate", "hatax:ai-key-migrate"
    "HA Tax service:expense-scanner-enc", "hatax:expense-scanner-enc"
    "HA Tax service-export", "hatax-export"
    ".HA Tax service", ".hatax"
    "HA Tax service-privacy-log", "hatax-privacy-log"
    "HA Tax service", "HATax"
    "HA Tax service", "hatax"
    "HA Tax service — Free Tax Preparation", "HATax — Professional Tax Preparation"
    "HA Tax service — Professional Tax Preparation", "HATax — Professional Tax Preparation"
    "Prepared by HA Tax service", "Prepared by HATax"
    "Generated by HA Tax service", "Generated by HATax"
    "HA Tax service Filing Packet", "HATax Filing Packet"
    "HA Tax service Deadlines", "HATax Deadlines"
    "HA Tax service//Tax Calendar", "HATax//Tax Calendar"
    "HA Tax service can generate", "HATax can generate"
    "HA Tax service is a preparation tool", "HATax is a preparation tool"
    "HA Tax service JSON export", "HATax JSON export"
    ".HA Tax service", ".hatax"
    "HA Tax service-export-", "hatax-export-"
    "format: 'HA Tax service-export'", "format: 'hatax-export'"
)

$count = 0
foreach ($file in $files) {
    $content = Get-Content -Path $file.FullName -Raw
    $original = $content
    
    for ($i = 0; $i -lt $replacements.Count; $i += 2) {
        $find = $replacements[$i]
        $replace = $replacements[$i + 1]
        $content = $content -replace [regex]::Escape($find), $replace
    }
    
    if ($content -ne $original) {
        Set-Content -Path $file.FullName -Value $content -Encoding UTF8
        $count++
        Write-Host "Updated: $($file.FullName)"
    }
}

Write-Host "Total files updated: $count"